# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the FastAPI code into the container
COPY . .

# Install curl, gnupg, and other required packages for ODBC
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    gcc g++ \
    unixodbc-dev \
    unixodbc \
    libpq-dev \
    build-essential


# Install the Microsoft ODBC Driver for SQL Server and accept EULA
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc


# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port 8000 (for FastAPI)
EXPOSE 8000

# Command to run the FastAPI app
CMD ["uvicorn", "fast_api:app", "--host", "0.0.0.0", "--port", "8000"]
